apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
  MONGO_URI: "mongodb+srv://srinidhisanjeevi:root123@docauth.ede9v4k.mongodb.net/dockerAuthDB?retryWrites=true&w=majority&appName=DocAuth"

  JWT_SECRET: "zapcominternsecret"